use crate::{FigurePattern, TextUnit, GeometryMatcher, Anchor, ElementClass, Grain, Operation, Direction, Transform, Locus};
use serde::{Serialize, Deserialize};

/// A concrete instantiation of a geometric signature.
/// Generated by LLM to demonstrate the geometric structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeometricWitness {
    pub hypothesis_id: String,
    pub instantiation: Vec<WitnessUnit>,
    pub transformation: Option<WitnessTransformation>,
    pub generator: String, // "llm" | "heuristic" | "manual"
    pub notes: Option<String>,
}

/// A single unit in the witness instantiation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessUnit {
    pub text: String,
    pub label: String,
    pub offset_start: usize,
    pub offset_end: usize,
    pub chunk_id: String,
}

/// Transformation shown in the witness
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessTransformation {
    pub before: String,
    pub after: String,
    pub operation: String,
    pub anchor: String,
    pub locus: String,
}

/// Result of LLM witness generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessGenerationResult {
    pub witness: GeometricWitness,
    pub confidence: f32,
    pub notes: Option<String>,
}

/// Request to LLM for witness generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessRequest {
    pub hypothesis_id: String,
    pub signature: GeometricSignature,
    pub prompt: String,
    pub examples: Vec<WitnessExample>,
}

/// Geometric signature for LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeometricSignature {
    pub operation: String,
    pub anchor: String,
    pub unit: String,
    pub locus: Option<String>,
    pub coordinate: Option<String>,
    pub repetition: usize,
    pub constraints: Vec<String>,
}

/// Example witness for few-shot prompting
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessExample {
    pub input: String,
    pub output: String,
    pub explanation: String,
}

/// Generate prompt for LLM witness generation
pub fn generate_witness_prompt(request: &WitnessRequest) -> String {
    let mut prompt = String::new();
    
    prompt.push_str("You are a geometric witness generator for rhetorical figures.\n\n");
    prompt.push_str("Your task: Given a geometric signature, produce a concrete textual example that instantiates the signature WITHOUT knowing the figure's name.\n\n");
    
    prompt.push_str(&format!("GEOMETRIC SIGNATURE:\n"));
    prompt.push_str(&format!("  Operation: {}\n", request.signature.operation));
    prompt.push_str(&format!("  Anchor: {}\n", request.signature.anchor));
    prompt.push_str(&format!("  Unit: {}\n", request.signature.unit));
    if let Some(locus) = &request.signature.locus {
        prompt.push_str(&format!("  Locus: {}\n", locus));
    }
    if let Some(coord) = &request.signature.coordinate {
        prompt.push_str(&format!("  Coordinate: {}\n", coord));
    }
    prompt.push_str(&format!("  Repetition: {}\n", request.signature.repetition));
    if !request.signature.constraints.is_empty() {
        prompt.push_str(&format!("  Constraints: {}\n", request.signature.constraints.join(", ")));
    }
    
    prompt.push_str("\nEXAMPLES:\n");
    for (i, ex) in request.examples.iter().enumerate() {
        prompt.push_str(&format!("Example {}:\n", i + 1));
        prompt.push_str(&format!("  Input: {}\n", ex.input));
        prompt.push_str(&format!("  Output: {}\n", ex.output));
        prompt.push_str(&format!("  Explanation: {}\n", ex.explanation));
    }
    
    prompt.push_str("\nYOUR TASK:\n");
    prompt.push_str("Produce a concrete textual example that instantiates the above geometric signature.\n");
    prompt.push_str("Do NOT use the figure's name. Only show the geometric transformation.\n");
    prompt.push_str("Return JSON: { \"witness\": { \"instantiation\": [...], \"transformation\": {...} } }\n");
    
    prompt
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WitnessValidation {
    pub hypothesis_id: String,
    pub witness: GeometricWitness,
    pub user_judgment: UserJudgment,
    pub revision: Option<Revision>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UserJudgment {
    Faithful,
    IncorrectGeometry,
    Revise,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Revision {
    pub field: String,
    pub old_value: String,
    pub new_value: String,
    pub reason: String,
}
